version: '3.8'
services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: 8a23e2aea1030c802aa62e413a29add54388efa3756c87117b9bbb07421d58c8
    environment:
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - rabbitmq
    volumes:
      - ./:/app/
  rabbitmq:
    image: rabbitmq:3.6.6
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_VHOST=
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - redis
  redis:
    image: redis
    ports:
    - "6379:6379"